### ISSUE TITLE
Help with YAML Formatting?

### ISSUE THREAD

**Issue by maarxx** [flecmart/keep2todoist#2]
Hello:

Thanks for this! Looks awesome. But I'm having trouble with the YAML formatting, getting apparent syntax errors.

Can you please help?

I just wanted to map my Google Lists to Todoist Lists as follows:

Task -> Tasks
To-Do -> Tasks
Shopping -> Shopping List

and all due 1 year ago.

```
update_interval_s: 60
google_username: a
google_password: b
todoist_api_token: c
keep_lists:
  - Todo:
    due_str_en: '1 year ago'
  - 'Shopping'
    todoist_project: 'Shopping List'
  - 'Task'
    todoist_project: 'Tasks'
  - 'To-Do'
    todoist_project: 'Tasks'
```

```
keep2todoist  | INFO:root:Loading configuration...
keep2todoist  | ERROR:root:Could not load configuration: while parsing a block collection
keep2todoist  |   in "config.yaml", line 6, column 3
keep2todoist  | expected <block end>, but found '<block mapping start>'
keep2todoist  |   in "config.yaml", line 9, column 5
keep2todoist  | Traceback (most recent call last):
keep2todoist  |   File "/app/./app.py", line 52, in <module>
keep2todoist  |     config = load_configuration()
keep2todoist  |   File "/app/./app.py", line 14, in load_configuration
keep2todoist  |     return config
keep2todoist  | UnboundLocalError: local variable 'config' referenced before assignment
keep2todoist exited with code 1
```

**Comment by maarxx** [comment]
No this is something else, I've found that even if I completely delete my config.yaml file, I still get the same error, specifically citing lines and columns in the file.

**Comment by flecmart** [comment]
The root cause of the error seems to be invalid yaml. For what you describing the config should look sth like this:

```yaml
update_interval_s: 60
google_username: a
google_password: b
todoist_api_token: c
keep_lists:
  - Task:
    todoist_project: Tasks
  - Shopping:
    todoist_project: 'Shopping List'
  - To-Do:
    todoist_project: 'Tasks'
```

The due_str_en is optional for every list, so if you want to set a due date on the todoist entries you can go like this:

```yaml
update_interval_s: 60
google_username: a
google_password: b
todoist_api_token: c
keep_lists:
  - Task:
    todoist_project: Tasks
    due_str_en: today
  - Shopping:
    todoist_project: 'Shopping List'
    due_str_en: today
  - To-Do:
    todoist_project: 'Tasks'
    due_str_en: today
```
