### ISSUE TITLE
Adding Keep tasks NOT in lists to Todoist?

### ISSUE THREAD

**Issue by BusterMcGeee** [flecmart/keep2todoist#20]
I apologize if there's a better way to contact you than creating an Issue. First off, thank you yet again for this script. We were talking last month or so about my getting to run as a service on Windows and I've gotten two instances of it running beautifully.

So, I've noticed that Google Assistant has a hard time parsing many of my "add X to my Y list" commands as requests to add X to a List, especially when X includes prepositions. "Hey Google, make a note, Z" seems to be much more reliable but as you know that command can only add Z as a Note in Keep, not as an item on a List. 

Would it be easily possible to add a feature to Keep2todoist to send all orphan Keep Notes (notes not part of Lists) to Todoist, as well as items on Lists?

**Comment by flecmart** [comment]
Hey,

no problem in opening issues, allthough, Depending on my spare time it can take a while until I respond 😄 

I think I don't yet undertstand the problem. Are the notes in keep that you want to add items to actually lists?
The ones with the squares where you can check each item:

![image](https://user-images.githubusercontent.com/10167243/223960331-4954024e-d28f-481a-8177-a238ad149cb3.png)

For me that works absolutely reliable if I say sth like "Add X to my Test Labels list" (referring to the example in the picture). I even can say sth like 'Hey Google, add milk, butter and salt to my shopping list' and google would add those 3 items independently to my shopping list.

Did you try that?

It would definately be possible to implement this feature but I am not sure if I like it, because it is a little bit out of scope of what I had planned initially and I don't really see an advantage in implementing this. I am open to being convinced, but don't have a lot of spare time at the moment.

**Comment by BusterMcGeee** [comment]
Hey, thanks so much for responding.

I'll start with the issue I have with Google Assistant adding things to
Google Keep: In short, having to add tasks to *lists *limits the length and
usefulness of the tasks I can add.

If I'm just asking it to add single items to a list, e.g. milk, butter,
salt, it works beautifully. However, the notes/tasks I want to add to
Todoist tend to be longer, like "Hey Google, add 'talk to builders about
changing the flooring,' to my to-do list," or "talk with Scott about
changing the deadline." Google Assistant has a hard time parsing longer
notes/tasks like this, especially with prepositions.

This might be because the "Hey Google, add X to my Y list" syntax is more
optimised for adding single items to lists rather than taking longer notes.
Its "Hey Google, make a note, X" syntax seems much more optimised for
longer notes, rather than adding short items to a list. The problem that
arises with using that latter syntax with Google Assistant is that it
doesn't add 'X' to an existing Keep list that can be transferred by
Keep2todoist- it adds it as a separate, untitled note:

[image: Keep test 3.png]

[image: Keep test 4.png]

I was hoping there was a way for Keep2todoist to transfer notes that are *not
part of existing lists *to Todoist as well. Am I making any sense? I do
foresee the issue of not being able to differentiate *notes *from
*lists *themselves
(*notes *apparently just being *lists *without titles or checkboxes) but
perhaps Keep *lists *look different than untitled *notes *behind the scenes?

Anyway, if this isn't a feature you have the time or interest in pursuing,
I understand! We all miss the golden age of using IFTTT to perfect this
process and I'm grateful for any way at all to integrate Assistant and
Todoist. Thanks again for giving this to us.

Langdon

**Comment by flecmart** [comment]
Hey again, 

thanks for the explenation. I see your point now. I don't really use gkeep that way but I understand that it would be useful to have this feature.

It might be possible to find just untitled notes from google keep and add them all to some configured todoist project or the inbox in todoist or sth like that. However, I want the additional configuration to be as minimal as possible...

maybe sth like this? (optional untitled_notes block)

```yaml
update_interval_s: 60
google_username: yourUsername
google_password: canBeAnAppPassword
todoist_api_token: todoistApiKey
healthcheck: # optional: configure some kind of healtcheck endpoint providing service monitoring, e.g. https://healthchecks.io/
  url: https://hc-ping.com/someuuid
  period_min: 30
untitled_notes: # optional? would move all untitled notes to todoist inbox, or a project if specified
  due_str_en: 'today' # optional: you can set a due date in english here
  # if todoist_project is not set your task will go into the todoist inbox
keep_lists:  # list your keep lists on this level
  - Todo:
      sync_labels: false # required: transfer labels from gkeep lists to todoist items
      due_str_en: 'today' # optional: you can set a due date in english here
      # if todoist_project is not set your task will go into the todoist inbox
  .
  .
  .
```

Definately doable. But it propably takes me some time to implement and test because I have to find free time for that. I'll just leave that issue open for me as reference.
