### ISSUE TITLE
Feature Request: Add Labels

### ISSUE THREAD

**Issue by maarxx** [flecmart/keep2todoist#3]
Feature Request: Add Labels

Like, similarly to the due date, add another key to the yaml per list, to add a Label.

**Comment by flecmart** [comment]
This can be done I guess with the following:

-https://developer.todoist.com/rest/v1/#create-a-new-task
- https://developer.todoist.com/rest/v1/#labels

It involves more logic than the due date, though.

- there can be multiple labels so the yaml wood be sth like:

```yaml
.
.
.
keep_lists:
  - Todo:
    todoist_project: Einkaufsliste
    labels:
      - labelA
      - labelB
```

Then

1. get all Labels from todoist rest api with ids
2. for every label check if it allready exists on todoist side (if not -> create)
3. parse yaml labels and map them to corresponding tasks

I might do this when I have some free time, but at the moment I don't have a lot. If you wanna implement this, feel free to open a PR :-)

If I may ask - for what usecase do you use labels?
