### ISSUE TITLE
Manifest Unknown

### ISSUE THREAD

**Issue by TBTHEDBA** [flecmart/keep2todoist#50]
I keep getting Manifest unknown when trying to pull the docker image. 

![image](https://github.com/flecmart/keep2todoist/assets/40796990/730f0d21-4dee-4de5-b721-e3315be5cc47)

**Comment by TBTHEDBA** [comment]
It is removing them intermittingly. I will continue to monitor to see if I can find a pattern.

**Comment by flecmart** [comment]
Hmm, I never observed something like that.
Some questions that might help debugging:

- Are you using notes or lists in gkeep?
- Do you see any error output on the console?
- In which environment do you run the app?
- Are you using an app password for google authentication?

**Comment by TBTHEDBA** [comment]
- This is for Shopping List only. I would like to use notes if I can get it working reliably though. 

- I've attached my most recent run.
[Error.txt](https://github.com/flecmart/keep2todoist/files/13501573/Error.txt)

- Running in docker using a locally downloaded and composed container as I couldn't get your prebuilt image to work. Kept getting the following error 
- Pulling from flecmart/keep2todoist
docker: manifest unknown.

- Yes I am using the App password.

**Comment by flecmart** [comment]
Thanks for the details. So the manifest unknown was really weird and I could confirm that on my end. I don't know what happened, but all the docker images seemed to be corrupted somehow. 

I rebuilt the latest image and that fixed this - so maybe you can try running the docker image again.

Looking at your error output there seems to be an error with the todoist side:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.todoist.com/rest/v2/tasks`

Is that only happening for yuo shopping list? How is the todoist project named exactly? Maybe this is some edge case that yields to this bad request. The app is restarting then again and goes in a loop - I guess I should add some exception handling here to improve this and make the error output clearer.

Can you give some more details so that I can try to reproduce this behavior? Does it only happen for shopping list?

**Comment by TBTHEDBA** [comment]
Thank you again for looking into this so quickly. I really appreciate it. 

Shopping list is the only list I have in Keep and the only Project/List I have in Todoist. 

My main use of this is bypassing Googles change of only using Keep for its shopping list. I am going to eventually put the todoist 
data into my homeassistant.

**Comment by TBTHEDBA** [comment]
I created a new test account on todoist.

The items are **now being deleted** from my keep but the app is still restarting at the same point and throwing the same error. 

2023-11-29 11:49:59 2023-11-29 17:49:59 app-INFO:       -> 
2023-11-29 11:50:00 Traceback (most recent call last):
2023-11-29 11:50:00   File "/app/app.py", line 222, in <module>
2023-11-29 11:50:00     update()
2023-11-29 11:50:00   File "/app/app.py", line 198, in update
2023-11-29 11:50:00     transfer_untitled_notes(parse_key(untitled_notes_options, 'add_label'), parse_key(untitled_notes_options, 'due_str_en'))
2023-11-29 11:50:00   File "/app/app.py", line 179, in transfer_untitled_notes
2023-11-29 11:50:00     todoist_api.add_task(content=untitled_note.text, due_string=due, due_lang='en', labels=todoist_labels)
2023-11-29 11:50:00   File "/venv/lib/python3.11/site-packages/todoist_api_python/api.py", line 59, in add_task
2023-11-29 11:50:00     task = post(self._session, endpoint, self._token, data=data)
2023-11-29 11:50:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-29 11:50:00   File "/venv/lib/python3.11/site-packages/todoist_api_python/http_requests.py", line 47, in post
2023-11-29 11:50:00     response.raise_for_status()
2023-11-29 11:50:00   File "/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2023-11-29 11:50:00     raise HTTPError(http_error_msg, response=self)
2023-11-29 11:50:00 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.todoist.com/rest/v2/tasks

**Comment by flecmart** [comment]
Is this also using the docker image now? If not can you try that, too
please?

Also can you share your config.yaml? Without API token and Google password
of course.

I'll stop working on it for today but I will look into it the other day...
I want to make this more robust for myself so thanks for the debug Infos.

TBTHEDBA ***@***.***> schrieb am Mi., 29. Nov. 2023, 18:51:

**Comment by TBTHEDBA** [comment]
This is my first time using docker and I wasn't able to get your "Pre-built docker image" instructions to work for me. 

Here is my config (renamed to .txt to allow upload) and just for full picture the error I get when trying to install with "Pre-built docker image"

[error.txt](https://github.com/flecmart/keep2todoist/files/13505869/error.txt)
[config.txt](https://github.com/flecmart/keep2todoist/files/13505878/config.txt)

**Comment by TBTHEDBA** [comment]
I did get the "latest Image" running. Same error. It's at least "working" for sync at the moment though. 

Had to learn how to add files to an image on windows. 

Really need to get a dedicated system going for docker if I am going to conti

**Comment by flecmart** [comment]
Okay, 2 things I notice here:

The docker thing erroing was my bad. I got the command in the README.md slightly wrong.

Try: `docker run -v ./config.yaml:/app/config.yaml --restart always ghcr.io/flecmart/keep2todoist:latest` from the directory where the `config.yaml` is in.

Also from your config.yaml you have to strip everything from the example that does not match your lists. Try it with only your shopping lists:

```yaml
update_interval_s: 60
google_username: ----
google_password: -----
todoist_api_token: ----
healthcheck: # optional: configure some kind of healtcheck endpoint providing service monitoring, e.g. https://healthchecks.io/
  url: https://hc-ping.com/someuuid
  period_min: 30
untitled_notes: # optional: move all untitled notes to todoist inbox
  add_label: 'Sync' # required: add label to todoist note
  due_str_en: 'today' # optional: you can set a due date in english here
keep_lists:  # list your keep lists on this level
  - Shopping:
      sync_labels: false
      todoist_project: 'Shopping' # optional: you can choose a project for todoist here
```

Maybe the todoist api was throwing errors because it tried to access lists form my example config, that did not exist on your end?
